export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const SET_REGISTERATION_DATA = "SET_REGISTERATION_DATA";

export const SET_OTP_SEND = "SET_OTP_SEND";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAILURE = "OTP_FAILURE";

export const LOAD_REQUEST = "LOAD_REQUEST"
export const LOAD_SUCCESS = "LOAD_SUCCESS"
export const LOAD_FAILURE = "LOAD_FAILURE"


export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL" 
